import { inGamut, oklabToOklch, oklabToRgbTriple, oklchToOklab, toLinear, tripleToOklab } from '../colour.ts';

export const SHIPPED_SOURCES = Object.freeze({ primary: '#ffb545', secondary: '#8a7355', tertiary: '#006b68', neutral: { light: '#5c5a52', dark: '#243248' }, neutralVariant: { light: '#5f5b4f', dark: '#28364c' }, error: '#ba1a1a' });
export const SOURCE_FAMILIES = Object.freeze(['primary', 'secondary', 'tertiary', 'neutral', 'neutralVariant', 'error']);
const TONES = [0, 4, 6, 10, 12, 17, 20, 22, 24, 30, 40, 50, 60, 70, 80, 87, 90, 92, 94, 95, 96, 98, 99, 100];
const HEX = /^#[0-9a-f]{6}$/i;
const clamp01 = (value) => Math.min(1, Math.max(0, value));
const hexToRgb = (hex) => [0, 2, 4].map((at) => Number.parseInt(hex.slice(at + 1, at + 3), 16) / 255);
function cieLightness([red, green, blue]) { const y = 0.2126729 * toLinear(red) + 0.7151522 * toLinear(green) + 0.0721750 * toLinear(blue); return y <= 216 / 24389 ? y * (24389 / 27) : 116 * Math.cbrt(y) - 16; }
function toneAtHue(hue, sourceChroma, tone) {
  if (tone <= 0) return '#000000'; if (tone >= 100) return '#ffffff'; let low = 0, high = 1;
  for (let step = 0; step < 40; step += 1) { const middle = (low + high) / 2; const rgb = oklabToRgbTriple(oklchToOklab([middle, 0, hue])).map(clamp01); if (cieLightness(rgb) < tone) low = middle; else high = middle; }
  const lightness = (low + high) / 2; let usable = 0, tooMuch = Math.max(sourceChroma, 0.0001) * 1.2;
  for (let step = 0; step < 30; step += 1) { const middle = (usable + tooMuch) / 2; if (inGamut(oklabToRgbTriple(oklchToOklab([lightness, middle, hue])))) usable = middle; else tooMuch = middle; }
  const rgb = oklabToRgbTriple(oklchToOklab([lightness, Math.min(usable, sourceChroma), hue])).map(clamp01);
  return `#${rgb.map((channel) => Math.round(channel * 255).toString(16).padStart(2, '0')).join('')}`;
}
export function toneOf(sourceHex, tone) { if (!HEX.test(sourceHex)) throw new TypeError('Appearance token sources must be #rrggbb colours.'); const [, chroma, hue] = oklabToOklch(tripleToOklab(hexToRgb(sourceHex))); return toneAtHue(hue, chroma, tone); }
export const palette = (sourceHex) => Object.fromEntries(TONES.map((tone) => [tone, toneOf(sourceHex, tone)]));
export const ROLE_TONES = Object.freeze({
  light: { primary: ['primary', 40], 'on-primary': ['primary', 100], 'primary-container': ['primary', 90], 'on-primary-container': ['primary', 30], secondary: ['secondary', 40], 'on-secondary': ['secondary', 100], 'secondary-container': ['secondary', 90], 'on-secondary-container': ['secondary', 30], tertiary: ['tertiary', 40], 'on-tertiary': ['tertiary', 100], 'tertiary-container': ['tertiary', 90], 'on-tertiary-container': ['tertiary', 30], error: ['error', 40], 'on-error': ['error', 100], 'error-container': ['error', 90], 'on-error-container': ['error', 30], surface: ['neutral', 98], 'on-surface': ['neutral', 10], 'surface-variant': ['neutralVariant', 90], 'on-surface-variant': ['neutralVariant', 30], 'surface-dim': ['neutral', 87], 'surface-bright': ['neutral', 98], 'surface-container-lowest': ['neutral', 100], 'surface-container-low': ['neutral', 96], 'surface-container': ['neutral', 94], 'surface-container-high': ['neutral', 92], 'surface-container-highest': ['neutral', 90], 'inverse-surface': ['neutral', 20], 'inverse-on-surface': ['neutral', 95], 'inverse-primary': ['primary', 80], outline: ['neutralVariant', 50], 'outline-variant': ['neutralVariant', 80], scrim: ['neutral', 0], shadow: ['neutral', 0] },
  dark: { primary: ['primary', 80], 'on-primary': ['primary', 20], 'primary-container': ['primary', 30], 'on-primary-container': ['primary', 90], secondary: ['secondary', 80], 'on-secondary': ['secondary', 20], 'secondary-container': ['secondary', 30], 'on-secondary-container': ['secondary', 90], tertiary: ['tertiary', 80], 'on-tertiary': ['tertiary', 20], 'tertiary-container': ['tertiary', 30], 'on-tertiary-container': ['tertiary', 90], error: ['error', 80], 'on-error': ['error', 20], 'error-container': ['error', 30], 'on-error-container': ['error', 90], surface: ['neutral', 6], 'on-surface': ['neutral', 90], 'surface-variant': ['neutralVariant', 30], 'on-surface-variant': ['neutralVariant', 80], 'surface-dim': ['neutral', 6], 'surface-bright': ['neutral', 24], 'surface-container-lowest': ['neutral', 4], 'surface-container-low': ['neutral', 10], 'surface-container': ['neutral', 12], 'surface-container-high': ['neutral', 17], 'surface-container-highest': ['neutral', 22], 'inverse-surface': ['neutral', 90], 'inverse-on-surface': ['neutral', 20], 'inverse-primary': ['primary', 40], outline: ['neutralVariant', 60], 'outline-variant': ['neutralVariant', 30], scrim: ['neutral', 0], shadow: ['neutral', 0] },
});
function familySources(seed, sources) { const seedColour = HEX.test(seed) ? seed : SHIPPED_SOURCES.primary; const result = { ...SHIPPED_SOURCES, primary: seedColour }; for (const [name, colour] of Object.entries(sources ?? {})) if (SOURCE_FAMILIES.includes(name) && HEX.test(colour)) result[name] = colour; return result; }
export function schemeForSeed(seedHex, dark, sources = {}) { const families = familySources(seedHex, sources); const scheme = dark ? 'dark' : 'light'; const roles = {}; for (const [role, [family, tone]] of Object.entries(ROLE_TONES[scheme])) { const source = families[family]; const colour = typeof source === 'string' ? source : source[scheme]; roles[`--md-sys-color-${role}`] = palette(colour)[tone]; } return roles; }
export function roleValue(scheme, role, sources = SHIPPED_SOURCES) { const [family, tone] = ROLE_TONES[scheme][role]; const source = sources[family]; return palette(typeof source === 'string' ? source : source[scheme])[tone]; }
